config/routes.rb
Rails.application.routes.draw do

  get 'team_photos/new'

  post 'team_photos/create'

  resources :teams do
    get 'communities', to: "communities#index"
    post 'team_albums/new'
    post 'team_albums/create'
    patch 'team_albums/create'
  end

end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :team_albums
  mount_uploader :cover_image, TeamCoverUploader
end

app/models/team_album.rb
class TeamAlbum < ActiveRecord::Base
  belongs_to :team
  has_many :team_photos
  accepts_nested_attributes_for :team_photos
end

app/models/team_photo.rb
class TeamPhoto < ActiveRecord::Base
  belongs_to :team_album
  mount_uploader :content, TeamPhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_team

  def index
  end

  private
  def set_team
    @team = Team.find(params[:team_id])
  end
end

app/controllers/team_albums_controller.rb
class TeamAlbumsController < ApplicationController
  before_action :set_team
  before_action :set_team_album, only: [:show, :edit, :update, :destroy]

  # GET /team_albums
  # GET /team_albums.json
  def index
    @team_albums = @team.team_albums.all
  end

  # GET /team_albums/1
  # GET /team_albums/1.json
  def show
  end

  # GET /team_albums/new
  def new
    @team_album = TeamAlbum.find(1)

    binding.pry
    team_photo_params[:team_photos].each do |file_content|
      @team_album.team_photos.build(file_content)
    end

    @team_album
  end

  # GET /team_albums/1/edit
  def edit
  end

  # POST /team_albums
  # POST /team_albums.json
  def create
    binding.pry
    @team_album = @team.team_albums.new(team_album_params)
    @team_album.save
  end

  # PATCH/PUT /team_albums/1
  # PATCH/PUT /team_albums/1.json
  def update
    respond_to do |format|
      if @team_album.update(team_album_params)
        format.html { redirect_to @team_album, notice: 'Team album was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_album }
      else
        format.html { render :edit }
        format.json { render json: @team_album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_albums/1
  # DELETE /team_albums/1.json
  def destroy
    @team_album.destroy
    respond_to do |format|
      format.html { redirect_to team_albums_url, notice: 'Team album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_team
      @team = Team.find(params[:team_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_team_album
      @team_album = @team.team_albums.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_album_params
      params.require(:team_album).permit(:name, :desc, :area)
    end

    def team_photo_params
      params.require(:team_album).permit({team_photos: [:content]})
    end
end

app/controllers/team_photos_controller.rb
class TeamPhotosController < ApplicationController
  def new
  end

  def create
    team_photo_params[:contents].each do

    end
  end

  private
  def team_photo_params
    params.require(:team_photo).permit({contents: []})
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :cover_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/team_albums_helper.rb
module TeamAlbumsHelper
end

app/helpers/team_photos_helper.rb
module TeamPhotosHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/communities/index.html.erb
<h1>Communities#index</h1>
<%= form_tag(team_team_albums_new_path(@team), multipart: true) do %>
  <div class="field">
    <%= file_field_tag :photos, multiple: true, name: "team_album[team_photos][][content]" %>
  </div>
  <div class="actions">
    <%= submit_tag "Upload" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FooCarrierwave</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/team_albums/_form.html.erb
<%= form_for(@team_album, url: {action: "create"}) do |f| %>
  <% if @team_album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@team_album.errors.count, "error") %> prohibited this team_album from being saved:</h2>

      <ul>
      <% @team_album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team_id %><br>
    <%= f.text_field :team_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <ul>
    <%= f.fields_for :team_photos do |photo_form| %>
      <li>
        <%= image_tag(photo_form.object.content_url) %>
        <%= photo_form.label :content %>
        <%= photo_form.file_field :content %>

        <%= photo_form.label :desc %>
        <%= photo_form.text_field :desc %>
      </li>
    <% end %>
  </ul>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/team_albums/edit.html.erb
<h1>Editing Team Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @team_album %> |
<%= link_to 'Back', team_team_albums_path %>

app/views/team_albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Team Albums</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Name</th>
      <th>Desc</th>
      <th>Area</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_albums.each do |team_album| %>
      <tr>
        <td><%= team_album.team %></td>
        <td><%= team_album.name %></td>
        <td><%= team_album.desc %></td>
        <td><%= team_album.area %></td>
        <td><%= link_to 'Show', team_album %></td>
        <td><%= link_to 'Edit', edit_team_team_album_path(@team, team_album) %></td>
        <td><%= link_to 'Destroy', team_album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team album', new_team_team_album_path %>

app/views/team_albums/new.html.erb
<h1>New Team Album</h1>

<%= render 'form' %>

app/views/team_albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @team_album.team %>
</p>

<p>
  <strong>Name:</strong>
  <%= @team_album.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @team_album.desc %>
</p>

<p>
  <strong>Area:</strong>
  <%= @team_album.area %>
</p>

<%= link_to 'Edit', edit_team_team_album_path(@team, @team_album) %> |
<%= link_to 'Back', team_team_albums_path %>

app/views/team_photos/create.html.erb
<h1>TeamPhotos#create</h1>
<p>Find me in app/views/team_photos/create.html.erb</p>

app/views/team_photos/new.html.erb
<h1>TeamPhotos#new</h1>
<%= form_tag({action: :create}, multipart: true) do %>
  <div class="field">
    <%= file_field_tag :photos, multiple: true, name: "team_photo[contents][]" %>
  </div>
  <div class="actions">
    <%= submit_tag "Upload" %>
  </div>
<% end %>